// Generated by Selenium IDE
package edu.pitt.cs;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.After;
import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless=new");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--remote-allow-origins=*");
        options.addArguments("--disable-features=SameSiteByDefaultCookies");
        options.addArguments("--disable-features=CookiesWithoutSameSiteMustBeSecure");
        options.addArguments("--disable-features=BlockInsecurePrivateNetworkRequests");
        options.addArguments("--disable-site-isolation-trials");

        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    private void setDefaultCookies() {
        driver.manage().deleteAllCookies();
        driver.manage().addCookie(new Cookie("1", "false"));
        driver.manage().addCookie(new Cookie("2", "false"));
        driver.manage().addCookie(new Cookie("3", "false"));
        driver.navigate().refresh();
    }

    @Test
    public void tEST1LINKS() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        WebElement element = driver.findElement(By.xpath("//a[contains(.,'Reset')]"));
        vars.put("resetLink", element.getAttribute("href"));
        assertEquals("http://localhost:8080/reset", vars.get("resetLink").toString());
    }

    @Test
    public void tEST2RESET() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));

        setDefaultCookies();

        driver.manage().addCookie(new Cookie("1", "true"));
        driver.manage().addCookie(new Cookie("2", "true"));
        driver.manage().addCookie(new Cookie("3", "true"));
        driver.navigate().refresh();

        driver.findElement(By.xpath("//a[contains(.,'Reset')]")).click();

        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[1]")).getText(), is("ID 1. Jennyanydots"));
        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
    }

    @Test
    public void tEST3CATALOG() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        List<WebElement> elements = driver.findElements(By.linkText("Catalog"));
        assert(elements.size() > 0);

        WebElement element = driver.findElement(By.cssSelector("li:nth-child(3) > img"));
        vars.put("imgSrc", element.getAttribute("src"));
        assertEquals("http://localhost:8080/images/cat2.jpg", vars.get("imgSrc").toString());
    }

    @Test
    public void tEST4LISTING() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        List<WebElement> elements1 = driver.findElements(By.xpath("//div[@id='listing']/ul/li[3]"));
        assert(elements1.size() > 0);

        List<WebElement> elements2 = driver.findElements(By.xpath("//div[@id='listing']/ul/li[4]"));
        assert(elements2.size() == 0);

        vars.put("Item3", driver.findElement(By.xpath("//div[@id='listing']/ul/li[3]")).getText());
        assertEquals("ID 3. Mistoffelees", vars.get("Item3").toString());
    }

    @Test
    public void tEST5RENTACAT() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.findElement(By.linkText("Rent-A-Cat")).click();

        assert(driver.findElements(By.xpath("//button[contains(.,'Rent')]")).size() > 0);
        assert(driver.findElements(By.xpath("//button[contains(.,'Return')]")).size() > 0);
    }

    @Test
    public void tEST6RENT() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.findElement(By.linkText("Rent-A-Cat")).click();
        driver.findElement(By.xpath("//input[@id='rentID']")).sendKeys("1");
        driver.findElement(By.xpath("//button[contains(.,'Rent')]")).click();

        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[1]")).getText(), is("Rented out"));
        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
        assertThat(driver.findElement(By.xpath("//div[@id='rentResult']")).getText(), is("Success!"));
    }

    @Test
    public void tEST7RETURN() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.manage().addCookie(new Cookie("2", "true"));
        driver.navigate().refresh();

        driver.findElement(By.linkText("Rent-A-Cat")).click();
        driver.findElement(By.xpath("//input[@id='returnID']")).sendKeys("2");
        driver.findElement(By.xpath("//button[contains(.,'Return')]")).click();

        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[1]")).getText(), is("ID 1. Jennyanydots"));
        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
        assertThat(driver.findElement(By.xpath("//div[@id='listing']/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
        assertThat(driver.findElement(By.xpath("//div[@id='returnResult']")).getText(), is("Success!"));
    }

    @Test
    public void tEST8FEEDACAT() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.findElement(By.linkText("Feed-A-Cat")).click();
        assert(driver.findElements(By.xpath("//button[contains(.,'Feed')]")).size() > 0);
    }

    @Test
    public void tEST9FEED() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.findElement(By.linkText("Feed-A-Cat")).click();
        driver.findElement(By.xpath("//input[@id='catnips']")).sendKeys("6");
        driver.findElement(By.xpath("//button[contains(.,'Feed')]")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.visibilityOfElementLocated(
                By.xpath("//*[@id='feedResult' and text()='Nom, nom, nom.']")));

        assertThat(driver.findElement(By.xpath("//div[@id='feedResult']")).getText(), is("Nom, nom, nom."));
    }

    @Test
    public void tEST10GREETACAT() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.findElement(By.xpath("//a[contains(text(),'Greet-A-Cat')]")).click();
        assertThat(driver.findElement(By.xpath("//div[@id='greeting']/h4")).getText(), is("Meow!Meow!Meow!"));
    }

    @Test
    public void tEST11GREETACATWITHNAME() {
        driver.get("http://localhost:8080");
        driver.manage().window().setSize(new Dimension(1440, 805));
        setDefaultCookies();

        driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
        assertThat(driver.findElement(By.xpath("//div[@id='greeting']/h4")).getText(),
                is("Meow! from Jennyanydots."));
    }
}